spring.application.name=Network-Monitor

spring.h2.console.enabled=true
# La ruta para entrar (por defecto es /h2-console)
spring.h2.console.path=/h2-console

# Fijar el nombre de la base de datos en memoria para que no cambie en cada reinicio
spring.datasource.url=jdbc:h2:mem:networkdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

networkmonitor.scan.subnet=
networkmonitor.scan.interval-ms=1800000

networkmonitor.scan.timing-template=-T4
networkmonitor.scan.host-timeout=60s
